apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: pacman-dev-clusters
  namespace: pacman
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev
