apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pacman-app
  name: pacman-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacman-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pacman-app
    spec:
    containers:
      - name: frontend
        image: "buniak/pacman"
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
